Unable to find image 'bit:5000/fengrl-torch1.0.1:latest' locally
latest: Pulling from fengrl-torch1.0.1
9ff7e2e5f967: Already exists
59856638ac9f: Already exists
6f317d6d954b: Already exists
a9dde5e2a643: Already exists
b03d58f382f0: Already exists
a7d5a9b04781: Already exists
e9a5dfa2bfd8: Already exists
4ae36dfee265: Already exists
f941c5b04e31: Already exists
9ee48d55afe8: Already exists
ca52f333e722: Already exists
5da54af39934: Already exists
a7691d1e444a: Pulling fs layer
a7691d1e444a: Verifying Checksum
a7691d1e444a: Download complete
a7691d1e444a: Pull complete
Digest: sha256:c7f776af39a65db9c66252e1d8da03f81b432d4ad30432956c4c35d5f7f391b3
Status: Downloaded newer image for bit:5000/fengrl-torch1.0.1:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/ghome/fengrl/home/biggan/torch-imp/biggan-torch/BigGAN-PyTorch-master/scripts/utils/prepare_data.sh\": permission denied": unknown.
